name: tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.version }}

    - name: Go version
      run: go version

    - name: Tests
      run: go test -v ./...

    - name: Race conditions
      run: go test -race -v ./...